In [1]:
import pandas as pd
import numpy as np
from numpy import cov

import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.colors import ListedColormap
# multivariate linear regression with regularization
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures

# support vector machine regression
from sklearn.svm import SVR
from sklearn.metrics import r2_score
# neural network
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout, Bidirectional, BatchNormalization
# normalization
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.pipeline import Pipeline
# score
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit, GridSearchCV, RandomizedSearchCV
# import keras
import tensorflow.keras
from tensorflow.keras import optimizers, regularizers
from tensorflow.keras.layers import Activation
from tensorflow.keras import backend as K
# import regularizer
from tensorflow.keras.regularizers import l1, l2
# import matplotlib
import matplotlib.pyplot as plt
# os
# randomseed

from numpy.random import seed
from numpy import asarray
from numpy import savetxt
###############################3
import os
import pickle
from calendar import monthrange


In [2]:
tensorflow.random.set_seed(0)

In [3]:
area_df     = pd.read_excel('area_2003-2019.xls', sheet_name = 'Sheet1')
lychee_yield_df = pd.read_excel('lycheeproduct.xlsx')
humidChiangrai=pd.read_excel('humidchiangrai.xlsx',sheet_name = 'Sheet2')
tempchiangrai=pd.read_excel('temperaturechiangrai.xlsx',sheet_name = 'Sheet2')
rainchiangrai=pd.read_excel('rainchiangrai.xlsx')
tempchiangrai=tempchiangrai.iloc[:,0:12]
humidChiangrai=humidChiangrai.iloc[:,0:12]
print(tempchiangrai)

JAN   FEB   MAR   APR   MAY   JUN   JUL   AUG   SEP   OCT   NOV   DEC
0   19.9  21.0  24.2  27.0  26.6  27.4  26.8  27.0  26.4  24.9  21.4  20.5
1   20.2  21.7  24.8  27.2  26.6  27.2  26.3  26.3  26.8  25.9  22.1  19.1
2   19.5  22.8  24.7  27.1  27.5  27.0  27.2  27.0  27.1  26.4  23.0  20.5
3   21.9  22.3  24.5  28.5  29.0  28.6  27.4  26.7  26.7  25.9  22.6  21.8
4   20.8  22.0  23.6  25.7  26.7  27.4  27.2  26.3  26.7  25.6  22.4  20.3
5   20.6  22.8  24.6  27.5  27.4  27.6  26.5  26.9  26.5  26.1  25.2  22.1
6   21.1  24.1  24.2  28.5  28.2  27.6  26.8  26.7  26.3  24.5  24.0  18.5
7   19.3  22.0  24.6  27.3  27.9  28.0  26.9  26.5  26.8  25.8  24.1  20.9
8   19.6  21.7  25.1  26.4  28.5  28.7  27.7  27.2  27.2  25.6  24.6  21.7
9   19.0  21.6  26.1  29.5  28.9  27.5  26.8  27.1  27.1  26.5  24.6  21.7
10  21.5  22.8  25.9  26.7  27.6  27.8  26.8  27.1  27.0  26.1  24.2  20.7
11  21.0  22.6  24.7  25.9  27.0  27.1  27.3  26.8  27.3  26.1  23.1  22.5


In [4]:
rainchiangrai=pd.read_excel('cm_met_ChiangRai.xlsx',sheet_name='Rainfall')
pressurechiangrai=pd.read_excel('cm_met_ChiangRai.xlsx',sheet_name='Pressure')
pheno=pd.read_excel('cm_met_Chiangrai.xlsx',sheet_name='pheno')

rainchiangrai=rainchiangrai.iloc[0,1:]
rainchiangrai=rainchiangrai.to_numpy()
rainchiangrai=rainchiangrai.reshape(12,13)
rainchiangrai=np.delete(rainchiangrai,12,1)
###############################################3
pressurechiangrai=pressurechiangrai.iloc[0,1:]
pressurechiangrai=pressurechiangrai.to_numpy()
pressurechiangrai=pressurechiangrai.reshape(12,13)
pressurechiangrai=np.delete(pressurechiangrai,12,1)
#########################################################
pheno=pheno.iloc[3,2:]
pheno=pheno.to_numpy()
pheno=pheno.reshape(12,12)
########################################################

inputchiangrai=pd.read_excel('input.xlsx')
Y_chiangrai=inputchiangrai.iloc[3:,3]
inputchiangrai=inputchiangrai.iloc[3:,:4]
inputchiangrai=inputchiangrai.to_numpy()
#######################################################################
Y_chiangrai=Y_chiangrai.to_numpy()
tempchiangrai=tempchiangrai.to_numpy()

humidChiangrai=humidChiangrai.to_numpy()

print(humidChiangrai.shape)

(12, 12)


In [5]:
####################DATAINPUT##########################################33
X_chiangrai=inputchiangrai[:,0:3]
X_chiangrai=np.concatenate((tempchiangrai[:,0:2],X_chiangrai),axis=1)
X_chiangrai=np.concatenate((X_chiangrai,pheno[:,0:2]),axis=1)
X_chiangrai=np.concatenate((X_chiangrai,rainchiangrai[:,2:4]),axis=1)
X_chiangrai=np.concatenate((X_chiangrai,humidChiangrai[:,0:2]),axis=1)
X_chiangrai=np.concatenate((X_chiangrai,pressurechiangrai[:,0:2]),axis=1)

In [6]:
######################################chiangmai####################################################################

In [7]:
inputchiagmai=pd.read_excel('inputchiangmai.xlsx')
tempchiangmai=pd.read_excel('cm_met_Chiangmai.xlsx',sheet_name='Temperature')
phenochiangmai=pd.read_excel('cm_met_Chiangmai.xlsx',sheet_name='Phenomena')
humidchiangmai=pd.read_excel('cm_met_Chiangmai.xlsx',sheet_name='Humidity')
rainchiangmai=pd.read_excel('cm_met_Chiangmai.xlsx',sheet_name='Rainfall')
pressurechiangmai=pd.read_excel('cm_met_Chiangmai.xlsx',sheet_name='Pressure')
Y_chiangmai=inputchiagmai.iloc[1:,3]



In [8]:
tempchiangmai=tempchiangmai.iloc[4,1:]
tempchiangmai=tempchiangmai.to_numpy()
tempchiangmai=tempchiangmai.reshape(13,13)
tempchiangmai=np.delete(tempchiangmai,9,0)
inputchiagmai=inputchiagmai.iloc[1:,:3]
#######################################################
phenochiangmai=phenochiangmai.iloc[3,1:]
phenochiangmai=phenochiangmai.to_numpy()
phenochiangmai=phenochiangmai.reshape(13,13)
phenochiangmai=np.delete(phenochiangmai,9,0)
########################################################


In [9]:
rainchiangmai=rainchiangmai.iloc[0,1:]
rainchiangmai=rainchiangmai.to_numpy()
rainchiangmai=rainchiangmai.reshape(13,13)
rainchiangmai=np.delete(rainchiangmai,12,1)
rainchiangmai=np.delete(rainchiangmai,9,0)
humidchiangmai=humidchiangmai.iloc[0,1:]
humidchiangmai=humidchiangmai.to_numpy()
humidchiangmai=humidchiangmai.reshape(13,13)
humidchiangmai=np.delete(humidchiangmai,12,1)

In [10]:

humidchiangmai=np.delete(humidchiangmai,9,0)
inputchiagmai=inputchiagmai.to_numpy()
Y_chiangmai=Y_chiangmai.to_numpy()
pressurechiangmai=pressurechiangmai.iloc[0,1:]
pressurechiangmai=pressurechiangmai.to_numpy()
pressurechiangmai=pressurechiangmai.reshape(13,13)
pressurechiangmai=np.delete(pressurechiangmai,12,1)
pressurechiangmai=np.delete(pressurechiangmai,9,0)
#X_chiangmai=tempchiangmai[:,0:2]
X_chiangmai=inputchiagmai[:,0:3]
X_chiangmai=np.concatenate((tempchiangmai[:,0:2],X_chiangmai,),axis=1)
X_chiangmai=np.concatenate((X_chiangmai,phenochiangmai[:,0:2]),axis=1)
X_chiangmai=np.concatenate((X_chiangmai,rainchiangmai   [:,2:4]),axis=1)
X_chiangmai=np.concatenate((X_chiangmai,humidchiangmai[:,0:2]),axis=1)
X_chiangmai=np.concatenate((X_chiangmai,pressurechiangmai[:,0:2]),axis=1)

In [11]:
X=X_chiangrai[:,[2,3,4,5,7,8,9,10,11,12]]
Tmp=X
Y=Y_chiangrai

In [12]:
print(X)

[[322.0 24.0 51211.0 1 28.9 213.8 69 63 1015.85 1012.96]
 [271.0 12.0 45982.0 0 40.4 178.9 76 73 1013.3 1012.37]
 [277.0 10.0 37228.0 0 31.9 52.1 72 68 1015.7 1010.2]
 [252.0 47.0 37228.0 1 23.9 89.8 72 63 1014.1 1011.7]
 [287.0 1.0 33938.0 1 91.9 84.8 75 67 1012.7 1010.5]
 [247.0 22.0 33586.0 1 37.5 104.7 75 68 1012.42 1009.22]
 [217.0 32.0 31916.0 1 59.1 2.2 76 75 1013.4 1011.6]
 [319.0 17.0 24290.0 0 6.4 131.7 77 66 1016.1 1010.7]
 [294.0 22.0 20476.0 0 22.4 191.8 75 69 1015.8 1012.9]
 [278.0 65.0 19426.0 0 0 4.8 73 68 1015.2 1015.2]
 [232.0 25.0 19316.0 0 12.2 160.9 80 68 1014.4 1013.1]
 [240.0 4.0 18624.0 0 35.6 136.6 78 70 1011.9 1012.5]]


In [13]:
print(X)

[[322.0 24.0 51211.0 1 28.9 213.8 69 63 1015.85 1012.96]
 [271.0 12.0 45982.0 0 40.4 178.9 76 73 1013.3 1012.37]
 [277.0 10.0 37228.0 0 31.9 52.1 72 68 1015.7 1010.2]
 [252.0 47.0 37228.0 1 23.9 89.8 72 63 1014.1 1011.7]
 [287.0 1.0 33938.0 1 91.9 84.8 75 67 1012.7 1010.5]
 [247.0 22.0 33586.0 1 37.5 104.7 75 68 1012.42 1009.22]
 [217.0 32.0 31916.0 1 59.1 2.2 76 75 1013.4 1011.6]
 [319.0 17.0 24290.0 0 6.4 131.7 77 66 1016.1 1010.7]
 [294.0 22.0 20476.0 0 22.4 191.8 75 69 1015.8 1012.9]
 [278.0 65.0 19426.0 0 0 4.8 73 68 1015.2 1015.2]
 [232.0 25.0 19316.0 0 12.2 160.9 80 68 1014.4 1013.1]
 [240.0 4.0 18624.0 0 35.6 136.6 78 70 1011.9 1012.5]]


In [14]:
Rootmean=tensorflow.keras.metrics.RootMeanSquaredError()

In [15]:
class Scaler3D():

    def __init__(self):
        self.scaler_list = {}

    def fit(self, x):
        self.x = x
        
        min_list = np.array([])
        max_list = np.array([])

        len_feature = x.shape[-1]

        for i in range(len_feature):
            self.scaler_list[i] = MinMaxScaler()
            self.scaler_list[i].fit(x[:, :, i])

    def transform(self, x):
        x_copy = x.copy()

        len_feature = x.shape[-1]

        for i in range(len_feature):
            x_copy[:,:,i] = self.scaler_list[i].transform(x[:, :, i])

        return x_copy

In [16]:
def rmse(y_true, y_pred):

    ind_ignorezero = (y_true != 0).reshape(-1,)
    error = (y_true - y_pred)
    se = error**2
    mse = np.mean(se)
    rmse = mse**0.5
    return rmse
def mape(y_true, y_pred):
    error = y_true - y_pred
    pe     = (y_true - y_pred)/y_true*100
    ape = np.abs(pe)
    mape = np.mean(ape)

    return mape  
def mae(y_true, y_pred):

    error = y_true - y_pred
    ae = np.abs(error)
    mae = np.mean(ae)

    return mae

In [17]:
n_size=X.shape[0]
X_train, X_test, Y_train, Y_test =  train_test_split(X, Y_chiangrai, test_size=0.3)
X_train_ord = X[:int(n_size*(1-0.3)), :]
X_test_ord  = X[int(n_size*(1-0.3)):, :]
Y_train_ord = Y[:int(n_size*(1-0.3))]
Y_test_ord  = Y[int(n_size*(1-0.3)):]

In [18]:
lin_reg = LinearRegression()
lin_reg.fit(X_train_ord, np.log1p(Y_train_ord))
Y_all_test = lin_reg.predict(X)
Y_all_test[Y_all_test<0] = 0

Y_all_test = np.expm1(Y_all_test)

train_mae = mae(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mae = mae(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_rmse = rmse(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_rmse = rmse(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

train_mape = mape(Y[:int(n_size*(1-0.3))], Y_all_test[:int(n_size*(1-0.3))])
test_mape = mape(Y[int(n_size*(1-0.3)):], Y_all_test[int(n_size*(1-0.3)):])

print('train MAE {:.2f}\ttest MAE {:.2f}'.format(train_mae, test_mae))
print('train RMSE {:.2f}\ttest RMSE {:.2f}'.format(train_rmse, test_rmse))
print('train MAPE {:.2f}\ttest MAPE {:.2f}'.format(train_mape, test_mape))
print('=========================')

train MAE 0.00	test MAE 1219.32
train RMSE 0.00	test RMSE 1303.17
train MAPE 0.00	test MAPE 22.05


In [19]:
print(X_train_ord)

[[322.0 24.0 51211.0 1 28.9 213.8 69 63 1015.85 1012.96]
 [271.0 12.0 45982.0 0 40.4 178.9 76 73 1013.3 1012.37]
 [277.0 10.0 37228.0 0 31.9 52.1 72 68 1015.7 1010.2]
 [252.0 47.0 37228.0 1 23.9 89.8 72 63 1014.1 1011.7]
 [287.0 1.0 33938.0 1 91.9 84.8 75 67 1012.7 1010.5]
 [247.0 22.0 33586.0 1 37.5 104.7 75 68 1012.42 1009.22]
 [217.0 32.0 31916.0 1 59.1 2.2 76 75 1013.4 1011.6]
 [319.0 17.0 24290.0 0 6.4 131.7 77 66 1016.1 1010.7]]


In [20]:
reg = l1(0.01)
neural = Sequential()
scaler=MinMaxScaler()
    # input layer
neural.add(Dense(20, activation='relu', input_dim=X.shape[1]))
    # hidden layer
neural.add(Dense(512, activation='relu',kernel_regularizer=reg)) 
#neural.add(Dropout(0.4))
neural.add(Dense(512, activation='relu',kernel_regularizer=reg))   
#neural.add(Dropout(0.4)) 
neural.add(Dense(512, activation='relu',kernel_regularizer=reg))   
#neural.add(Dropout(0.4))     
# output layer
neural.add(Dense(1, activation='relu'))
neural.compile(optimizer='adam', loss='mse',metrics=[Rootmean, 'mae', 'mape'])

In [21]:
scaler.fit(X_train_ord)
X_train=K.constant(X_train)
Y_train=K.constant(Y_train)
X_test=K.constant(X_test)
Y_test=K.constant(Y_test)
Y_train=K.constant(Y_train)
X_train_ord=K.constant(X_train_ord)
Y_train_ord=K.constant(Y_train_ord)
X_test_ord=K.constant(X_test_ord)
Y_test_ord=K.constant(Y_test_ord)
X=K.constant(X)

In [22]:
scaler.fit(X_train)
neural.fit(X_train_ord,Y_train_ord,epochs=100, verbose=1, batch_size=32)

Train on 8 samples
Epoch 1/100
8/8 [==============================] - 4s 485ms/sample


InternalError:  Blas GEMM launch failed : a.shape=(8, 10), b.shape=(10, 20), m=8, n=20, k=10
	 [[node sequential/dense/MatMul (defined at C:\Users\ASUS\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference_distributed_function_1278]

Function call stack:
distributed_function


In [23]:
y_pred=neural.predict(K.constant(X))
y_pred=y_pred.reshape(12,)


In [1]:
print(y_pred)

NameError: name 'y_pred' is not defined

In [2]:
accuracy=neural.evaluate(X_train_ord, Y_train_ord)

NameError: name 'neural' is not defined

In [3]:
accuracy=neural.evaluate(X_test_ord, Y_test_ord)

NameError: name 'neural' is not defined

In [4]:
accuracy=neural.evaluate(K.constant(X),Y)


NameError: name 'neural' is not defined

In [5]:
reg = l1(0.02)
neural2 = Sequential()
scaler=MinMaxScaler()
    # input layer
neural2.add(Dense(256, activation='relu', input_dim=X.shape[1]))
    # hidden layer
neural.add(Dropout(0.2))
neural2.add(Dense(512, activation='relu',kernel_regularizer=reg)) 
neural.add(Dropout(0.2))
neural2.add(Dense(512, activation='relu',kernel_regularizer=reg))   
neural.add(Dropout(0.2))
neural2.add(Dense(512, activation='relu',kernel_regularizer=reg))
neural.add(Dropout(0.2))   
neural2.add(Dense(512, activation='relu',kernel_regularizer=reg))  
# output layer
neural2.add(Dense(1, activation='relu'))
neural2.compile(optimizer='adam', loss='mse',metrics=[Rootmean, 'mae', 'mape'])

NameError: name 'l1' is not defined

In [6]:
neural2.fit(X_train_ord,Y_train_ord,epochs=100, verbose=1, batch_size=32)

NameError: name 'neural2' is not defined

In [7]:
y_pred=neural2.predict(X)
print(y_pred)

NameError: name 'neural2' is not defined

In [8]:
accuracy=neural2.evaluate(X_train_ord, Y_train_ord)

NameError: name 'neural2' is not defined

In [9]:
accuracy=neural2.evaluate(X_test_ord, Y_test_ord)

NameError: name 'neural2' is not defined

In [10]:
####################################################GRU#############################

In [11]:
X=Tmp

NameError: name 'Tmp' is not defined

In [12]:
X=X.reshape(X.shape[0],1,X.shape[1])

NameError: name 'X' is not defined

In [13]:
n_size=X.shape[0]

X_train, X_test, Y_train, Y_test =  train_test_split(X, Y, test_size=0.3)
X_train_ord = X[:int(n_size*(1-0.3)), :,:]
X_test_ord  = X[int(n_size*(1-0.3)):, :,:]
Y_train_ord = Y[:int(n_size*(1-0.3))]
Y_test_ord  = Y[int(n_size*(1-0.3)):]

NameError: name 'X' is not defined

In [14]:

X_train=K.constant(X_train)
Y_train=K.constant(Y_train)
X_test=K.constant(X_test)
Y_test=K.constant(Y_test)
Y_train=K.constant(Y_train)
X_train_ord=K.constant(X_train_ord)
Y_train_ord=K.constant(Y_train_ord)
X_test_ord=K.constant(X_test_ord)
Y_test_ord=K.constant(Y_test_ord)
X=K.constant(X)

NameError: name 'K' is not defined

In [15]:
tensorflow.random.set_seed(0)

NameError: name 'tensorflow' is not defined

In [16]:
rnn = Sequential()
rnn.add(GRU(100, activation='relu', return_sequences=True, input_shape=(X.shape[1],X.shape[2])))
#rnn.add(Dropout(0.4))
rnn.add(GRU(100, activation='relu', return_sequences=True))
rnn.add(Dropout(0.4))
#rnn.add(GRU(100, activation='relu'))    
    # rnn.add(BatchNormalization())    
#rnn.add(Dropout(0.4))
rnn.add(Dense(50, activation='relu'))
#rnn.add(Dropout(0.4))    
rnn.add(Dense(1, activation='relu'))
rnn.compile(optimizer='adam', loss='mse',metrics=[Rootmean, 'mae', 'mape'])

NameError: name 'Sequential' is not defined

In [17]:
rnn.fit(X_train, Y_train_ord, epochs=100, batch_size=32, verbose=1)

NameError: name 'rnn' is not defined

In [18]:
y_pred1=rnn.predict(X)
y_pred1=y_pred1.reshape(12,)
print(y_pred1)

NameError: name 'rnn' is not defined

In [19]:
accuracy=rnn.evaluate(X_train,Y_train)

NameError: name 'rnn' is not defined

In [20]:
accuracy=rnn.evaluate(X_test, Y_test)

NameError: name 'rnn' is not defined

In [21]:
########################LSTMแบบที่1######

In [22]:
#rnn_LSTM = Sequential()
#rnn_LSTM.add(LSTM(20, activation='relu', return_sequences=True, input_shape=(X.shape[1],X.shape[2])))
#rnn_LSTM.add(Dropout(0.2))
#rnn_LSTM.add(LSTM(50, activation='relu',return_sequences=True,))
#rnn_LSTM.add(Dropout(0.2))
#rnn_LSTM.add(LSTM(50, activation='relu',return_sequences=True,))
#rnn_LSTM.add(Dropout(0.2))
#rnn_LSTM.add(LSTM(50, activation='relu',return_sequences=True,))
#rnn_LSTM.add(Dropout(0.2))
#rnn_LSTM.add(Dense(50, activation='relu'))
#rnn_LSTM.add(Dense(1, activation='relu'))
#rnn_LSTM.compile(optimizer='adam', loss='mse',metrics=[Rootmean, 'mae', 'mape'])

In [23]:
#rnn_LSTM.fit(X_train_ord, Y_train_ord, epochs=100, batch_size=32, verbose=1)

In [24]:
#accuracy=rnn_LSTM.evaluate(X_train, Y_train_ord)

In [25]:
#accuracy=rnn_LSTM.evaluate(X_test, Y_test_ord)

In [26]:
rnn_LSTM2 = Sequential()
rnn_LSTM2.add(LSTM(256, activation='relu', return_sequences=True, input_shape=(X.shape[1],X.shape[2])))
rnn_LSTM2.add(Dropout(0.2))
rnn_LSTM2.add(LSTM(512, activation='relu',return_sequences=True))
rnn_LSTM2.add(Dropout(0.2))
rnn_LSTM2.add(LSTM(512, activation='relu',return_sequences=True))
rnn_LSTM2.add(Dropout(0.2))
#rnn_LSTM2.add(LSTM(50, activation='relu',return_sequences=True))
rnn_LSTM2.add(Dropout(0.2))
rnn_LSTM2.add(Dense(512, activation='relu'))
#rnn_LSTM.add(Dropout(0.2))
rnn_LSTM2.add(Dense(1, activation='relu'))
rnn_LSTM2.compile(optimizer='adam', loss='mse',metrics=[Rootmean, 'mae', 'mape'])

NameError: name 'Sequential' is not defined

In [27]:
rnn_LSTM2.fit(X_train_ord,Y_train_ord, epochs=100, batch_size=32, verbose=1)

NameError: name 'rnn_LSTM2' is not defined

In [28]:
accuracy=rnn_LSTM2.evaluate(X_train_ord, Y_train_ord)

NameError: name 'rnn_LSTM2' is not defined

In [29]:
accuracy=rnn_LSTM2.evaluate(X_test_ord, Y_test_ord)

NameError: name 'rnn_LSTM2' is not defined

In [30]:
GruChiangmai = Sequential()
GruChiangmai.add(GRU(10, activation='relu', return_sequences=True, input_shape=(X.shape[1],X.shape[2])))

GruChiangmai.add(GRU(50, activation='relu', return_sequences=True))

GruChiangmai.add(GRU(50, activation='relu',return_sequences=True))    
GruChiangmai.add(GRU(50, activation='relu',return_sequences=True))   
    # rnn.add(BatchNormalization())    
#GruChiangmai.add(Dropout(0.4))
GruChiangmai.add(Dense(50, activation='relu'))
#GruChiangmai.add(Dropout(0.4))    
GruChiangmai.add(Dense(1, activation='relu'))
GruChiangmai.compile(optimizer='adam', loss='mse',metrics=[Rootmean, 'mae', 'mape'])

NameError: name 'Sequential' is not defined

In [31]:
GruChiangmai.fit(X_train_ord, Y_train_ord, epochs=100, batch_size=32, verbose=1)

NameError: name 'GruChiangmai' is not defined

In [32]:
accuracy=GruChiangmai.evaluate(X_train_ord, Y_train_ord)

NameError: name 'GruChiangmai' is not defined

In [33]:
accuracy=GruChiangmai.evaluate(X_test_ord, Y_test_ord)

NameError: name 'GruChiangmai' is not defined

In [34]:
y_GRU=GruChiangmai.predict(X)


NameError: name 'GruChiangmai' is not defined

In [35]:
print(y_GRU)

NameError: name 'y_GRU' is not defined

In [36]:
plt.style.use('ggplot')
n = X_chiangmai.shape[0]

fig, ax = plt.subplots()
index = np.arange(n)
bar_width = 0.35
opacity = 0.9
ax.bar(index, Y, bar_width, alpha=opacity, color='r',
                label='Y_True')
ax.bar(index+bar_width, y_GRU.reshape(12,), bar_width, alpha=opacity, color='b',
                label='Y_predict')
ax.set_xlabel('Year ')
ax.set_ylabel('AmountTon')
ax.set_title('Y_chiangmai with model LSTM')
ax.set_xticks(index + bar_width / 2)
ax.set_xticklabels(('2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018'
    ))
ax.legend()
plt.show()

NameError: name 'plt' is not defined

In [37]:
##############################RNN#########################################################

In [38]:
########################################FeatureSelection##########################